### ISSUE TITLE
No coffeescript in clipboard

### ISSUE THREAD

**Issue by livando** [asimpson/js2coffee-alfred-workflow#1]
1) copy known working javascript, http://jsfiddle.net/r7MgY/
2) run alfred JS2Coffee 
3) receive pompt to "Paste your fresh Coffee"
4) then nothing on the clipboard.

➥ node -v
v0.8.20
➥ npm -v
1.2.11

**Comment by asimpson** [comment]
The [latest binary](https://github.com/asimpson/js2coffee-alfred-workflow/releases/tag/v1.11) should fix this issue.

**Comment by livando** [comment]
works!

nice job, i'll be using this.

-d

btw...

[image: Inline image 1]

On Wed, Jul 10, 2013 at 9:48 PM, Adam Simpson notifications@github.comwrote:

> The latest binaryhttps://github.com/asimpson/js2coffee-alfred-workflow/releases/tag/v1.11should fix this issue.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/asimpson/js2coffee-alfred-workflow/issues/1#issuecomment-20785438
> .

## 

Don A. Livanec
